### PR TITLE
feat: homepage navbar

### PR DESCRIPTION
**Pull request by 3x071c**
✅ Fluid navigation bar at the top of the user-facing pages

### CODE REVIEW

**Comment by 3x071c** [comment]
Input on how we want to handle the responsive part of the Navbar would be appreciated! 💯

**Comment by simonwkla** [comment]
When hovering over links, their background doesnt change in light mode. This should be fixed, otherwise everything looks good to me. 

grafik
grafik

**Comment by 3x071c** [comment]
@Flosi23 The `LinkButton` background does vary slightly though: [#ebf8ff](https://www.color-hex.com/color/ebf8ff) in light mode, [#90cdf4](https://www.color-hex.com/color/90cdf4) in dark mode (at 12% opacity). These is default behavior, are you sure we should change that? I think it looks fine.

**Comment by 3x071c** [comment]
Converting to draft while fixing the apparent `Popover` misalignment issue

**Review by simonwkla — APPROVED** [review]

**Pull request merged**
